name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run
        run: |
          # Ensure the output directory exists
          mkdir -p out

          # Compile the Java code with all required JavaFX libraries
          javac --module-path libs/javafx-sdk/lib \
            --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.collections,javafx.scene,javafx.scene.control,javafx.scene.text \
            -d out src/application/*.java

          # Run the main application with JavaFX libraries
          java --module-path libs/javafx-sdk/lib \
            --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.collections,javafx.scene,javafx.scene.control,javafx.scene.text \
            -Djava.awt.headless=true -cp out application.Main
