name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run
        run: |
          # Ensure the output directory exists
          mkdir -p out
          
          # Compile the Java code with JavaFX libraries
          javac --module-path libs/javafx-sdk/lib --add-modules javafx.controls,javafx.fxml -d out src/application/*.java
          
          # Run the main application with JavaFX libraries
          java --module-path libs/javafx-sdk/lib --add-modules javafx.controls,javafx.fxml -cp out application.Main
