name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download JavaFX SDK
        run: |
          wget https://github.com/openjfx/openjfx/releases/download/20/javafx-sdk-20_linux-x64_bin.tar.gz
          tar -xvf javafx-sdk-20_linux-x64_bin.tar.gz
          mv javafx-sdk-20 /opt/javafx

      - name: Build and run
        run: |
          # Ensure the output directory exists
          mkdir -p out

          # Compile the Java code with JavaFX libraries
          javac --module-path /opt/javafx/lib --add-modules javafx.controls,javafx.fxml -d out src/application/*.java

          # Run the main application with JavaFX libraries
          java --module-path /opt/javafx/lib --add-modules javafx.controls,javafx.fxml -cp out application.Main
