name: Java CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK (default OpenJDK will be used, no need for 'distribution' input)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify Java 17

      # Compile and run your Java project (using javac directly)
      - name: Build and run
        run: |
          # Ensure the output directory exists
          mkdir -p out
          # Compile the Java code (adjust the source path as needed)
          javac -d out src/application/*.java
          # Run the main application (replace Main with your actual main class)
          java -cp out application.Main
