name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Download and Setup JavaFX SDK
        run: |
          wget https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_linux-x64_bin-sdk.zip
          unzip openjfx-17.0.2_linux-x64_bin-sdk.zip
          
          # Verify JavaFX libraries
          echo "Listing JavaFX libraries:"
          ls -l javafx-sdk-17.0.2/lib/*.jar
      
      - name: Prepare JavaFX Classpath
        run: |
          # Create a classpath with all JavaFX jars
          export JAVAFX_LIBS=$(find javafx-sdk-17.0.2/lib -name "*.jar" | tr '\n' ':')
          echo "JavaFX Classpath: $JAVAFX_LIBS"
      
      - name: Compile Java Application
        run: |
          # Ensure the output directory exists
          mkdir -p out
          
          # Compile with verbose output and explicit JavaFX jars
          javac \
            --module-path javafx-sdk-17.0.2/lib \
            --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.scene \
            -verbose \
            -d out src/application/*.java
      
      - name: Run Java Application
        run: |
          # Run with verbose module information
          java \
            --module-path javafx-sdk-17.0.2/lib \
            --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.scene \
            -Djava.awt.headless=true \
            -verbose:module \
            -cp out application.Main
