name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile Java Application
        run: |
          mkdir -p bin/application
          JAVAFX_LIBS="javafx-sdk-17.0.2/lib"
          JAVAFX_JARS=$(find "$JAVAFX_LIBS" -name "*.jar" | tr '\n' ':')
          javac --module-path "$JAVAFX_LIBS" --add-modules=ALL-MODULE-PATH -d bin/application src/application/*.java
      - name: Run Tests
        run: |
          # Add commands to run your tests here
