name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Download and Setup JavaFX SDK
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_linux-x64_bin-sdk.zip
          unzip openjfx-21.0.2_linux-x64_bin-sdk.zip
      
      - name: Compile Java Application
        run: |
          mkdir -p bin/application
          JAVAFX_LIBS="javafx-sdk-21.0.2/lib"
          javac --module-path "$JAVAFX_LIBS" --add-modules=ALL-MODULE-PATH \
                -d bin/application src/application/*.java

      - name: Copy Resources (FXML and CSS)
        run: |
          rsync -av --exclude='*.java' src/application/ bin/application/

      - name: Verify Resource Copy
        run: |
          echo "Looking for MainClient.fxml in bin/application"
          find bin/application -name "MainClient.fxml"
          echo "Looking for CSS files in bin/application"
          find bin/application -name "*.css"
          echo "Contents of bin/application:"
          ls -R bin/application

      - name: Debug Environment
        run: |
          echo "Environment Variables:"
          printenv
          echo "Contents of bin/application:"
          find bin/application

      - name: Install Accessibility Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y at-spi2-core
      
      - name: Install Xvfb for Headless Mode
        run: |
          sudo apt-get install -y xvfb

      - name: Run Java Application with Xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1024x768x24 &
          sleep 5
          JAVAFX_LIBS="javafx-sdk-21.0.2/lib"
          JAVAFX_JARS=$(find "$JAVAFX_LIBS" -name "*.jar" | tr '\n' ':')
          java --module-path "$JAVAFX_LIBS" --add-modules=ALL-MODULE-PATH \
               -cp bin/application:$JAVAFX_JARS application.Main
