name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Download and Setup JavaFX SDK
        run: |
          # Download JavaFX SDK
          wget https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_linux-x64_bin-sdk.zip
          unzip openjfx-17.0.2_linux-x64_bin-sdk.zip
          
          # Print library contents for debugging
          echo "JavaFX Library Contents:"
          find javafx-sdk-17.0.2/lib -name "*.jar"
      
      - name: Compile Java Application
        run: |
          # Create output directory (bin)
          mkdir -p bin/application
          
          # Prepare module path and classpath
          JAVAFX_LIBS="javafx-sdk-17.0.2/lib"
          JAVAFX_JARS=$(find "$JAVAFX_LIBS" -name "*.jar" | tr '\n' ':')
          
          # Compile with verbose output and explicit module configuration
          javac \
            --module-path "$JAVAFX_LIBS" \
            --add-modules=ALL-MODULE-PATH \
            --add-reads javafx.graphics=ALL-UNNAMED \
            --add-opens=java.base/java.lang=ALL-UNNAMED \
            --add-exports javafx.base/com.sun.javafx.event=ALL-UNNAMED \
            -d bin/application src/application/*.java
      
      - name: Copy Resources
        run: |
          # Copy all non-Java resources to bin/application while preserving structure
          rsync -av --exclude='*.java' src/application/ bin/application/
          echo "Copied Resources:"
          find bin/application/

      - name: Verify Resource Copy
        run: |
          find bin/application -name "MainClient.fxml"
          find bin/application -name "*.css"

      - name: Debug Environment
        run: |
          echo "Environment Variables:"
          printenv
          echo "Application Directory Contents:"
          ls -R bin/application
          echo "JavaFX Library Files:"
          find javafx-sdk-17.0.2/lib -name "*.jar"

      - name: Install Dependencies for dbind
        run: |
          sudo apt-get update
          sudo apt-get install -y at-spi2-core

      - name: Install Xvfb for Headless Mode
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Java Application with Xvfb
        run: |
          # Start Xvfb (virtual display)
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1024x768x24 &
          sleep 5
          
          # Prepare module path and classpath
          JAVAFX_LIBS="javafx-sdk-17.0.2/lib"
          JAVAFX_JARS=$(find "$JAVAFX_LIBS" -name "*.jar" | tr '\n' ':')
          
          # Run the application with proper classpath
          java \
            --module-path "$JAVAFX_LIBS" \
            --add-modules=ALL-MODULE-PATH \
            --add-reads javafx.graphics=ALL-UNNAMED \
            --add-opens=java.base/java.lang=ALL-UNNAMED \
            --add-exports javafx.base/com.sun.javafx.event=ALL-UNNAMED \
            -cp bin/application:$JAVAFX_JARS \
            -Djava.awt.headless=true application.Main
