name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK 17 (Temurin)
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # Download and Setup JavaFX SDK
      - name: Download and Setup JavaFX SDK
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_linux-x64_bin-sdk.zip
          unzip openjfx-21.0.2_linux-x64_bin-sdk.zip
      
      # Compile Java Application
      - name: Compile Java Application
        run: |
          mkdir -p bin/application
          JAVAFX_LIBS="javafx-sdk-21.0.2/lib"
          javac --module-path "$JAVAFX_LIBS" --add-modules=ALL-MODULE-PATH \
                -d bin/application src/application/*.java

      # Copy Resources (FXML and CSS)
      - name: Copy Resources (FXML and CSS)
        run: |
          rsync -av --exclude='*.java' src/application/ bin/application/

      # Check that all necessary files are present
      - name: Verify Resource Copy
        run: |
          find bin/application -name "*.java"
          find bin/application -name "*.fxml"
          find bin/application -name "*.css"
          echo "Listing contents of bin/application:"
          ls -R bin/application
