name: Java CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Download and Setup JavaFX SDK
        run: |
          wget https://download2.gluonhq.com/openjfx/17.0.2/openjfx-17.0.2_linux-x64_bin-sdk.zip
          unzip openjfx-17.0.2_linux-x64_bin-sdk.zip
          
      - name: Compile Java Application
        run: |
          mkdir -p bin
          JAVAFX_LIBS="javafx-sdk-17.0.2/lib"
          JAVAFX_JARS=$(find "$JAVAFX_LIBS" -name "*.jar" | tr '\n' ':')
          javac \
            --module-path "$JAVAFX_LIBS" \
            --add-modules=ALL-MODULE-PATH \
            -d bin src/application/*.java
      
      - name: Copy Resources
        run: |
          cp src/application/*.fxml src/application/*.css bin/

      - name: Verify Compiled Classes
        run: |
          echo "Compiled Classes:"
          find bin -name "*.class"

      - name: Install Xvfb for Headless Mode
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Java Application with Xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1024x768x24 &
          sleep 5
          JAVAFX_LIBS="javafx-sdk-17.0.2/lib"
          JAVAFX_JARS=$(find "$JAVAFX_LIBS" -name "*.jar" | tr '\n' ':')
          java \
            --module-path "$JAVAFX_LIBS" \
            --add-modules=ALL-MODULE-PATH \
            -cp bin:$JAVAFX_JARS \
            -Djava.awt.headless=true application.Main
