name: Java CI

on:
  push:
    branches:
      - main  # Or your default branch name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK (Java 17 in this case)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Install dependencies and run tests using Maven
      - name: Run tests
        run: |
          mkdir -p src/test/java/application
          # Manually compile and run tests using JUnit
          javac -cp .:junit-platform-console-standalone-1.7.2.jar src/test/java/application/DBConnectionTest.java
          java -cp .:junit-platform-console-standalone-1.7.2.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
